import { copyFileSync, existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { resolve, join } from 'node:path'
import matter from 'gray-matter'
import { z } from 'zod'

const ROOT = resolve(process.cwd())
const CONTENT_DIR = resolve(ROOT, 'content')
const DOCS_DIR = resolve(ROOT, 'docs')
const SRC_DATA_DIR = resolve(ROOT, 'src/data')

const PostFrontmatterSchema = z.object({
  title: z.string().min(1, '标题不能为空'),
  date: z.union([z.string(), z.date()]).transform((val) => {
    if (val instanceof Date) return val.toISOString().slice(0, 10)
    return val
  }),
  tags: z.array(z.string()).default([]),
  description: z.string().optional(),
  cover: z.string().optional(),
  category: z.string().optional(),
  draft: z.boolean().optional().default(false),
})

function formatDate(date) {
  if (!date) return ''
  return new Date(date).toISOString().slice(0, 10)
}

function getReadingTime(content, wordsPerMinute = 400) {
  let text = content
  text = text.replace(/^---[\s\S]*?---/, '')
  text = text.replace(/```[\s\S]*?```/g, '')
  text = text.replace(/`[^`]+`/g, '')
  text = text.replace(/!\[[^\]]*\]\([^)]*\)/g, '')
  text = text.replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')
  text = text.replace(/<[^>]+>/g, '')
  text = text.replace(/^[#>*_-]+\s*/gm, '')
  text = text.replace(/\s+/g, '')
  return Math.max(1, Math.ceil(text.length / wordsPerMinute))
}

function generatePostsData() {
  const postsDir = join(DOCS_DIR, 'posts')
  const files = readdirSync(postsDir).filter((f) => f.endsWith('.md') && f !== 'index.md')

  const posts = []
  for (const file of files) {
    const filepath = join(postsDir, file)
    const raw = readFileSync(filepath, 'utf-8')
    const { data, content } = matter(raw)

    if (!data.date) continue

    try {
      const validated = PostFrontmatterSchema.parse(data)
      if (validated.draft) continue

      const slug = file.replace(/\.md$/, '')
      posts.push({
        title: validated.title,
        url: `/posts/${slug}`,
        date: formatDate(validated.date),
        tags: validated.tags,
        description: validated.description ?? '',
        readingTime: getReadingTime(content),
        cover: validated.cover,
        category: validated.category,
        draft: validated.draft,
      })
    } catch (error) {
      console.warn(`Invalid frontmatter for post ${file}:`, error)
    }
  }

  posts.sort((a, b) => +new Date(b.date) - +new Date(a.date))

  if (!existsSync(SRC_DATA_DIR)) {
    mkdirSync(SRC_DATA_DIR, { recursive: true })
  }

  const tsContent = `// Auto-generated by scripts/copy-content.mjs — do not edit manually
export interface PostItem {
  title: string
  url: string
  date: string
  tags: string[]
  description: string
  readingTime: number
  cover?: string
  category?: string
  draft?: boolean
}

export const posts: PostItem[] = ${JSON.stringify(posts, null, 2)}

export function loadPosts(): PostItem[] {
  return posts
}
`

  writeFileSync(join(SRC_DATA_DIR, 'posts.ts'), tsContent, 'utf-8')
  console.log(`📊 Generated src/data/posts.ts with ${posts.length} posts`)
}

function copyPosts() {
  const srcPostsDir = join(CONTENT_DIR, 'posts')
  const destPostsDir = join(DOCS_DIR, 'posts')

  if (!existsSync(srcPostsDir)) {
    console.error('❌ content/posts directory not found. Did you run `git submodule update --init`?')
    process.exit(1)
  }

  if (!existsSync(destPostsDir)) {
    mkdirSync(destPostsDir, { recursive: true })
  }

  const files = readdirSync(srcPostsDir)
  let copied = 0

  for (const file of files) {
    if (!file.endsWith('.md')) continue
    const src = join(srcPostsDir, file)
    const dest = join(destPostsDir, file)
    copyFileSync(src, dest)
    copied++
  }

  console.log(`📄 Copied ${copied} posts to docs/posts/`)
}

function copyAbout() {
  const src = join(CONTENT_DIR, 'about.md')
  const dest = join(DOCS_DIR, 'about.md')

  if (!existsSync(src)) {
    console.error('❌ content/about.md not found.')
    process.exit(1)
  }

  copyFileSync(src, dest)
  console.log('📄 Copied about.md to docs/')
}

function copyPublic() {
  const srcPublicDir = join(CONTENT_DIR, 'public')
  const destPublicDir = join(DOCS_DIR, 'public')

  if (!existsSync(srcPublicDir)) {
    console.log('ℹ️ content/public directory not found, skipping.')
    return
  }

  if (!existsSync(destPublicDir)) {
    mkdirSync(destPublicDir, { recursive: true })
  }

  const files = readdirSync(srcPublicDir)
  let copied = 0

  for (const file of files) {
    const src = join(srcPublicDir, file)
    const dest = join(destPublicDir, file)
    // Skip og directory — generated at build time
    if (file === 'og') continue
    copyFileSync(src, dest)
    copied++
  }

  console.log(`📄 Copied ${copied} public assets to docs/public/`)
}

function main() {
  console.log('📦 Copying content from submodule...\n')
  copyPosts()
  copyAbout()
  copyPublic()
  generatePostsData()
  console.log('\n✅ Content copy complete.')
}

main()
