// Auto-generated by scripts/copy-content.mjs — do not edit manually
export interface PostItem {
  title: string
  url: string
  date: string
  tags: string[]
  description: string
  readingTime: number
  cover?: string
  category?: string
  draft?: boolean
}

export const posts: PostItem[] = [
  {
    "title": "从零到一：在 Ubuntu 24.04 上搭建 Kubernetes v1.35 与 Rancher 管理平台",
    "url": "/posts/2026-05-20-k8s-rancher-setup-guide",
    "date": "2026-05-20",
    "tags": [
      "kubernetes",
      "rancher",
      "devops"
    ],
    "description": "在单节点 Ubuntu 服务器上，从零安装 Kubernetes v1.35 到 Rancher 容器管理平台部署的全过程，涵盖镜像加速、Ingress 优化等实战经验。",
    "readingTime": 3,
    "category": "运维",
    "draft": false
  },
  {
    "title": "AI Agent 开发者学习路径整理",
    "url": "/posts/2026-04-14-ai-agent-learning-resources",
    "date": "2026-04-14",
    "tags": [
      "AI Agent",
      "Dify",
      "LangChain",
      "LangGraph",
      "向量数据库",
      "RAG"
    ],
    "description": "面向开发者的 AI Agent 学习路径，覆盖 Agent 基础、Dify 平台、LangChain/LangGraph 框架和向量数据库选型，含推荐学习顺序和最小实践路线。",
    "readingTime": 7,
    "cover": "/og/default.png",
    "draft": false
  },
  {
    "title": "Dify 1.14 Docker 服务架构解析",
    "url": "/posts/2026-04-14-dify-docker-architecture",
    "date": "2026-04-14",
    "tags": [
      "Dify",
      "Docker",
      "向量数据库",
      "LLM",
      "AI 平台"
    ],
    "description": "梳理 Dify 1.14 的 Docker Compose 服务架构，包括核心服务、可选数据库和向量数据库的 profile 切换方式。",
    "readingTime": 3,
    "cover": "/og/default.png",
    "draft": false
  },
  {
    "title": "MarkItDown：微软开源的文件转 Markdown 工具",
    "url": "/posts/2026-04-14-markitdown-tool",
    "date": "2026-04-14",
    "tags": [
      "工具",
      "Markdown",
      "文档转换",
      "Python",
      "AI 编码"
    ],
    "description": "介绍微软开源的 MarkItDown 工具，支持将 PDF、Word、Excel、PPT 等文件转换为 Markdown，适合 AI 处理和知识库整理。",
    "readingTime": 2,
    "cover": "/og/default.png",
    "draft": false
  },
  {
    "title": "用 Codex 和 Claude Code 两天做一个 Next.js + Supabase 导航站：NavSphere 项目复盘",
    "url": "/posts/2026-04-08-navsphere-codex-claude-code",
    "date": "2026-04-08",
    "tags": [
      "Next.js",
      "Supabase",
      "Codex",
      "Claude Code",
      "Vercel",
      "项目复盘"
    ],
    "description": "复盘 NavSphere 这个开发者导航站项目：技术栈、架构设计、部署方式，以及用 Codex 和 Claude Code 把一个可运行全栈项目压缩到两天内完成的真实体感。",
    "readingTime": 12,
    "cover": "/og/default.png",
    "category": "AI 开发",
    "draft": false
  },
  {
    "title": "Claude Code 深度指南（长篇版）",
    "url": "/posts/2026-03-30-longform-guide-claude-code",
    "date": "2026-03-30",
    "tags": [
      "Claude Code",
      "AI",
      "开发工具",
      "效率"
    ],
    "description": "深入探讨 Claude Code 的高级使用技巧：Token 经济学、记忆持久化、动态系统提示注入、持续学习、子代理编排、评估基准测试、MCP 替代策略、并行实例管理等。",
    "readingTime": 23,
    "category": "工具链",
    "draft": false
  },
  {
    "title": "Claude Code 速查指南（Everything Claude Code）",
    "url": "/posts/2026-03-30-shorthand-guide-claude-code",
    "date": "2026-03-30",
    "tags": [
      "Claude Code",
      "AI",
      "开发工具",
      "效率"
    ],
    "description": "经过 10 个月日常使用后，关于 Claude Code 的完整配置总结：技能、钩子、子代理、MCP、插件，以及真正有效的工作流。",
    "readingTime": 6,
    "category": "工具链",
    "draft": false
  },
  {
    "title": "用 VitePress + Tailwind 搭一个更适合 AI 的博客",
    "url": "/posts/2026-03-28-hello-vitepress-tailwind",
    "date": "2026-03-28",
    "tags": [
      "VitePress",
      "TailwindCSS",
      "Codex"
    ],
    "description": "一套适合开发者和 AI 写作工作流的博客模板。",
    "readingTime": 1,
    "cover": "/og/default.png",
    "draft": false
  },
  {
    "title": "我为什么放弃 NotionNext，转向 Obsidian + Codex + VitePress + ESA",
    "url": "/posts/2026-03-28-obsidian-codex-vitepress-esa-blog",
    "date": "2026-03-28",
    "tags": [
      "Obsidian",
      "Codex",
      "VitePress",
      "TailwindCSS",
      "博客"
    ],
    "description": "一套更适合 AI 时代开发者的博客写作与发布方案：Obsidian 写作、Codex 辅助、VitePress 构建、ESA 部署。",
    "readingTime": 9,
    "cover": "/og/default.png",
    "category": "工具链",
    "draft": false
  },
  {
    "title": "中兴5228F解决IPV6问题",
    "url": "/posts/2025-02-01-zte-5228f-ipv6",
    "date": "2025-02-01",
    "tags": [
      "中兴",
      "IPv6",
      "交换机",
      "网络"
    ],
    "description": "中兴5228F交换机配置IPv6后设备无法获取地址的解决方法。",
    "readingTime": 2,
    "draft": false
  },
  {
    "title": "PlayCover和金铲铲之战下载地址分享",
    "url": "/posts/2024-08-22-playcover-jinchantang",
    "date": "2024-08-22",
    "tags": [
      "PlayCover",
      "macOS",
      "iOS应用",
      "游戏"
    ],
    "description": "PlayCover和金铲铲之战在Mac上的下载地址分享。",
    "readingTime": 1,
    "draft": false
  }
]

export function loadPosts(): PostItem[] {
  return posts
}
